# Numpy


# Creation Of Array

In [4]:
mylst=[1, 2, 3]
print(mylst)

[1, 2, 3]


In [9]:
import numpy as np
array=np.array(mylst, dtype=int)
print(array)
print(type(array))

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
print(len(array))
print(array.ndim)
print(array.shape)

3
1
(3,)


In [11]:
array2=array.reshape(3,1)
print(array2)

[[1]
 [2]
 [3]]


In [14]:
lst1=[1, 2, 3]
lst2=[4, 5, 6]
lst3=[7, 8, 9]
arr=np.array([lst1, lst2, lst2])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [4 5 6]]
(3, 3)


In [15]:
r=range(24)
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [16]:
a1=a.reshape(8, 3)
print(a1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [17]:
print(a1.ndim)

2


In [18]:
print(a1.shape)

(8, 3)


In [19]:
x=np.array([[1, 2], [3,4]])
y=np.array([[1, 2], [3,4]])
print(x+y)

[[2 4]
 [6 8]]


In [20]:
print(x-y)

[[0 0]
 [0 0]]


In [21]:
print(x*y)


[[ 1  4]
 [ 9 16]]


In [22]:
print(x.dot(y))


[[ 7 10]
 [15 22]]


In [23]:
print(np.sum(x))

10


In [ ]:
print(np.sum(x, axis=0)) # each col sum

[4 6]


In [ ]:
print(np.sum(x, axis=1))  # each row sum

[3 7]
