In [ ]:
#numeric int, float
#10, 10.53
#characters
#strings
#"kritish_21"

#numeric types
# int, int64 #numeric chars 
# float, float64 # with dec
#64 bits equivalent to 8bytes

#chars type
#category and object



# Checking data types of eachcol


## syntax=> df.dtypes

In [1]:
import pandas as pd
car_data=pd.read_csv("toyota.csv")
car_data.dtypes

Price         int64
Age           int64
KM            int64
FuelType     object
HP            int64
MetColor      int64
Automatic     int64
CC            int64
Doors         int64
Weight        int64
dtype: object

In [2]:
car_data

Price  Age     KM FuelType   HP  MetColor  Automatic    CC  Doors  \
0     13500   23  46986   Diesel   90         1          0  2000      3   
1     13750   23  72937   Diesel   90         1          0  2000      3   
2     13950   24  41711   Diesel   90         1          0  2000      3   
3     14950   26  48000   Diesel   90         0          0  2000      3   
4     13750   30  38500   Diesel   90         0          0  2000      3   
...     ...  ...    ...      ...  ...       ...        ...   ...    ...   
1431   7500   69  20544   Petrol   86         1          0  1300      3   
1432  10845   72  19000   Petrol   86         0          0  1300      3   
1433   8500   71  17016   Petrol   86         0          0  1300      3   
1434   7250   70  16916   Petrol   86         1          0  1300      3   
1435   6950   76      1   Petrol  110         0          0  1600      5   

      Weight  
0       1165  
1       1165  
2       1165  
3       1165  
4       1170  
...      ...  
1431    1025  
1432    1015  
1433    1015  
1434    1015  
1435    1114  

[1436 rows x 10 columns]

# Count of unique data types
### get_dtype_counts()

In [8]:
car_data.dtypes.value_counts()


int64     9
object    1
Name: count, dtype: int64

# Selecting data types based on data types
### df.select_dtypes(include=None, exclude=None)

In [10]:
car_data.select_dtypes(include="int64", exclude="object")

Price  Age     KM   HP  MetColor  Automatic    CC  Doors  Weight
0     13500   23  46986   90         1          0  2000      3    1165
1     13750   23  72937   90         1          0  2000      3    1165
2     13950   24  41711   90         1          0  2000      3    1165
3     14950   26  48000   90         0          0  2000      3    1165
4     13750   30  38500   90         0          0  2000      3    1170
...     ...  ...    ...  ...       ...        ...   ...    ...     ...
1431   7500   69  20544   86         1          0  1300      3    1025
1432  10845   72  19000   86         0          0  1300      3    1015
1433   8500   71  17016   86         0          0  1300      3    1015
1434   7250   70  16916   86         1          0  1300      3    1015
1435   6950   76      1  110         0          0  1600      5    1114

[1436 rows x 9 columns]

In [11]:
car_data.select_dtypes(include="object", exclude="int64")

FuelType
0      Diesel
1      Diesel
2      Diesel
3      Diesel
4      Diesel
...       ...
1431   Petrol
1432   Petrol
1433   Petrol
1434   Petrol
1435   Petrol

[1436 rows x 1 columns]

# Concise summary of a dataframe
### data type of index
### data type of col
### count non null values
### memory usage
### syntax=> df.info()


In [12]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Price      1436 non-null   int64 
 1   Age        1436 non-null   int64 
 2   KM         1436 non-null   int64 
 3   FuelType   1436 non-null   object
 4   HP         1436 non-null   int64 
 5   MetColor   1436 non-null   int64 
 6   Automatic  1436 non-null   int64 
 7   CC         1436 non-null   int64 
 8   Doors      1436 non-null   int64 
 9   Weight     1436 non-null   int64 
dtypes: int64(9), object(1)
memory usage: 112.3+ KB


# Unique elements of col
### unique()
### numpy.unique(array)

In [13]:
import numpy as np
print(np.unique(car_data["KM"]))

[     1     15    225 ... 218118 232940 243000]


In [14]:
print(np.unique(car_data["HP"]))

[ 69  71  72  73  86  90  97  98 107 110 116 192]


In [15]:
print(np.unique(car_data["MetColor"]))

[0 1]


In [16]:
print(np.unique(car_data["Doors"]))

[2 3 4 5]
